server:
  port: 8023

spring:
  application:
    name: recruitment
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,public/**
      preserve-session: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/study?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update  # create, update
    show-sql: true
    properties:
      hibernate:
        format_sql: true



